### ISSUE TITLE
image loading

### ISSUE THREAD

**Issue by Drasek** [OpenDataMap/opendatamap#11]
Webpack file-loader or url-loader, which to use to load static image files?

**Comment by labcode-de** [comment]
I think we use file-loader

**Comment by Drasek** [comment]
Would love to have a marker for the gateways (atm not available as svg) and later maybe images of the routers, or so?

**Comment by labcode-de** [comment]
Yes, Good Idea

**Comment by labcode-de** [comment]
Can we close the Issue?
